### ISSUE TITLE
Cannot change loading image size

### ISSUE THREAD

**Issue by gerapicon** [arierie/pageloader#2]
Error:(42, 40) Dimension types not allowed (at 'setLoadingImageHeight' with value '64dp').

**Comment by andre8888** [comment]
same here.

**Comment by arierie** [comment]
Hi Andre and gerapicon

I'm sorry for late respond, i will check it later. Thank you for your
contribution, i really appreciate it. Hopefully it will fix soon.

Best Regards,

Arie Ridwansyah

**Comment by gencaysahinn** [comment]
Any result about this bug?

**Comment by arierie** [comment]
I'm sorry, but i'm not yet check it. I will check it soon.

**Comment by arierie** [comment]
Dear gerapicon, andre8888 , and gencaysahinn

First, i want to say sorry for low responds. After i checked the code, i see there is no bug you just wrong wrote. In java and xml has a different dimension, it's only use integer not followed by dp/sp. But, thank you for your attention. I really appreciate it.

Best Regards,

Arie Ridwansyah
